### ISSUE TITLE
Form.controls value null if not using ngModel

### ISSUE THREAD

**Issue by youngzkyz** [ng2-ui/ng2-datetime-picker#109]
Thanks before,

I have been test for my component if i dont using ([ngModel]).  the form dont detect changes so the value still null or not changed.

[here check my plunker](https://plnkr.co/edit/FA0Dot0poSa36uiGwcI8?p=preview)

How to solve this?

Thanks,

**Comment by allenhwkim** [comment]
Thanks for feedback

Please take a look at this example, https://rawgit.com/ng2-ui/ng2-datetime-picker/master/app/index.html

I am not sure this is the right approach, but to make it work, you need to have `formControlName="xxx"` for the input field.

        <input formControlName="birthDate" ng2-datetime-picker>

https://plnkr.co/edit/W5YtoN?p=preview

This is currently how we get a AbstractControl for the input field, but I am not sure this is the right approach.

https://github.com/ng2-ui/ng2-datetime-picker/blob/master/src/ng2-datetime-picker.directive.ts#L111

I would appreciate if you suggest any thing we can make use of `[formControl]`, instead of not common usage of `formControlName`
