### ISSUE TITLE
string conversion

### ISSUE THREAD

**Issue by vknaveenkumar** [ng2-ui/ng2-datetime-picker#125]
when i use json.stringify it shows both date and time . i want only date

**Comment by allenhwkim** [comment]
Please be more specific with an example, or else this will be closed

**Comment by vknaveenkumar** [comment]
when using this directives it return in the form of date format  in the  [(ngModel)] . what   i want is it should return the  only  date as string  .

**Comment by vinagreti** [comment]
I'm having the same issue. I'm passing a string to ngModel and after any change, the ngModel value become a Date object instead string. The same does not occur if we not change the date.

**Comment by allenhwkim** [comment]
Please use `date-only="true"` as specified in README.md

![image](https://cloud.githubusercontent.com/assets/1437734/22511504/e63c46bc-e863-11e6-9311-2065a373e7ec.png)

**Comment by vinagreti** [comment]
I am doing this but did not work.... Still getting the same problem. See the plunker that shows the problem.

https://plnkr.co/edit/2mTkb6b0btmR33EkV0r3?p=preview

**Comment by allenhwkim** [comment]
This is datetime picker, it should and must return a Date, not string.
If you want string just add `''+`, e.g., ''+myVar`

**Comment by vinagreti** [comment]
I think you are wrong saying this is a datepicker not a string picker. In my point of view (and angular point too), there are many ways to represent a Date, and string is one of them. If you just ignore this, you will end up loosing some users because they have JSON with ISO String dates and don't want to parse it before or after manipulate. If you accept a string as date, you should also delivery a date as string. None form component should change a type, only manipulates a variable, not changing it's type.

I've made another component to handle this, parsing the date after picking one in the datepicker but it is not a what we suppose to do when sing a component that was built to do this. It is like you are doing half work...

Besides my point of view, you did a grate work with this and helped me a lot. I would not try another datepicker if string was supported, but this static DATE output is going to force me go find another datepicker. As I dont want to do this, I ask you if it is possible for you to change it and return date in the same format the input were. If string, return a string as you did in previous releases. Just in ISO format, not any other format that require a strong logic, so you can only to a toString() before returning the value... Thanks a lot for your attention.

**Comment by allenhwkim** [comment]
@vinagreti 
The main point of this module is to get date and output format from user, and return the date as formatted. If no formatting is required, it's not the design of this module although it can be easily done. 

Although it can be easily done, I am not sure how many users want this feature.

**Comment by vinagreti** [comment]
Thanks @allenhwkim . I'll improve the question with more arguments and start a new issue.

**Comment by vknaveenkumar** [comment]
can u fix the issue that make the datepicker output as string without any formattting
