### ISSUE TITLE
ngModel not updated when selecting only time

### ISSUE THREAD

**Issue by Krisa** [ng2-ui/ng2-datetime-picker#17]
It looks like ngModel is not updated on the latest version (currently 0.6.0) when a time on the slider is selected and the popup is closed. However, when changing additionally the date, it works as expected.

**Comment by allenhwkim** [comment]
Thanks for reporting this.

**Comment by Krisa** [comment]
Apart from this, would it be maybe a good occasion to support also formControl, independently of ngModel?

**Comment by Krisa** [comment]
looks like the time is updated again (just tested in 0.8). Not sure whether it's because of the RC6 or you did anything. Closing anyway this issue.

**Comment by allenhwkim** [comment]
Thanks for your patience, I made some changes for this.

 About `ngModel`, I can think of some output event, so that when value is change, we can have some callback. e.g. `(valueChanged)="myCallback($event)`

I do not heavily use `formControl`, so I am not confident on using this, but any PR would be welcome.
