### ISSUE TITLE
Not Getting SRC folder

### ISSUE THREAD

**Issue by DILEEPKUMAREBIX** [ng2-ui/ng2-datetime-picker#43]
On using '$ npm install ng2-datetime-picker --save' , i am not getting src foler. I want to modify dateTimePicker as per my requirement.

**Comment by allenhwkim** [comment]
Thanks for reporting this.
src folder is intentionally removed from npm because it's not part of package.
And, I do not recommend to modify source in `node_modules` since it will be over-written anytime soon by your command.

You still can source code from  `git clone https://github.com/ng2-ui/ng2-datetime-picker.git`
