### ISSUE TITLE
How to set options?

### ISSUE THREAD

**Issue by andrashatvani** [ng2-ui/ng2-datetime-picker#66]
* First day of week i.e. Monday instead of Sunday and
* Don't hide picker in case focus will be lost

**Comment by allenhwkim** [comment]
* First day of week i.e. Monday instead of Sunday and
This uses momentJS. You can change moment localedata for it.
https://github.com/ng2-ui/ng2-datetime-picker/blob/master/src/datetime.ts#L65

* Don't hide picker in case focus will be lost
  * I don't see a good use case for this. If you just want to have a static datetime picker without input field, you still can do it using DateTimePickerComponnent only without using DateTimePickerDirective. It's designed to be used separately.
https://github.com/ng2-ui/ng2-datetime-picker/blob/master/src/datetime-picker.component.ts

**Comment by andrashatvani** [comment]
Awesome, thanks! 
Can the weekends be treated as weekdays?

**Comment by allenhwkim** [comment]
@andrashatvani it's just styling issue. You can override the style.

**Comment by andrashatvani** [comment]
@allenhwkim Yes, please extend the documentation with the locale setup with moment.

**Comment by andrashatvani** [comment]
@allenhwkim Yes, please extend the documentation with the locale setup with moment.
I couldn't make it work with the following code:

```typescript
import Moment = moment.Moment;
let moment:Moment = require('moment');
// and by setting in the constructor of the app module:
moment.locale('de');
// although the locale will be set:
console.log(moment.locale());
// output: de

**Comment by andrashatvani** [comment]
@allenhwkim Please provide examples for including the datetime picker as a component. I tried it as follows, but without success:
```html
    <datetime-picker
            [(ngModel)]="myDate"
            date-only="true"
            ngDefaultControl></datetime-picker>

**Comment by allenhwkim** [comment]
@andrashatvani thanks for trying

I will provide examples, but you gotta wait. I need to find some free time to do this.

**Comment by andrashatvani** [comment]
@allenhwkim Ok, until then I'll clone and adapt it. Thanks in advance.

**Comment by allenhwkim** [comment]
Here is the example only with Ng2DateTimePickerComponent.

https://plnkr.co/edit/DqRdjFRUi3vaivb42oaq?p=preview

LMK if you need more.
